# Generated by Django 5.2.1 on 2025-05-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='link',
            field=models.CharField(default='https://ejemplo.com', max_length=200),
        ),
    ]
